config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end

    resources :dashboards, only: %i[index]
    root 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :flowers
    resources :questions
    resources :monthly_themes
    resources :theme_resources
  end

  resources :self_esteem_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :self_discovery_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :diaries
  resource :mypage, only: %i[show]
  resource :garden, only: %i[show]
  root 'static_pages#top'
  get 'top', to:'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :questions, only: [:index] do
    collection do
      post :calculate
      get :result
    end
  end
  resources :encouragement_requests, only: %i[index new create show edit update destroy] do
    resources :encouragement_messages, only: [:index]
    collection do
      get 'select_image'
      get 'draft'
    end
    member do
      patch 'status_update'
    end
  end
  resources :encouragement_messages, only: %i[ new create show edit update destroy]
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
  has_many :diary_entries, dependent: :destroy
  validates :date, presence: true
  validates :date,
            uniqueness: {
              scope: :user_id,
              message: lambda { |_object, data|
                " #{data[:value]}の日記はすでに作成済みです"
              }
            }
  def self.ransackable_attributes(_auth_object = nil)
    ['created_at']
  end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  before_action :set_q, only: [:index]

  def index
    @diaries = @q.result(distinct: true).includes(:diary_entries).order(created_at: :desc)
  end

  def new
    @date = Date.current
    @diary_form = DiaryForm.new
  end

  def create
    @date = Date.current
    @diary_form = DiaryForm.new(diary_form_params.merge(user_id: current_user.id))

    if @diary_form.save
      redirect_to diaries_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @entries = @diary.diary_entries
  end

  def edit
    @diary_form = DiaryForm.new(diary: @diary)
  end

  def update
    @diary_form = DiaryForm.new(diary_form_params, diary: @diary)
    if @diary_form.update
      redirect_to diary_path(@diary.id), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @diary.destroy!
    redirect_to diaries_path, success: t('.success')
  end

  private

  def set_diary
    @diary = current_user.diaries.find(params[:id])
  end

  def diary_form_params
    params.require(:diary_form).permit(entries_contents: [], entries_ids: [])
  end

  def set_q
    @q = current_user.diaries.ransack(params[:q])
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
  def total_entries
    3
  end
end

app/views/diaries/_diary.html.erb
<div class="bg-customBeige3 border-dashed border-2 border-customGreen7 rounded-xl mt-6 lg:mt-0 lg:mb-6 lg:px-4 py-4 lg:py-0 lg:flex lg:items-center lg:justify-center">
  <div class="border-customGreen7 border-b-2 text-center pb-2 lg:border-none lg:w-2/12 text-center">
    <h2><%= diary.date %>（<%= I18n.l(diary.date, format: '%a') %>）</h2>
  </div>
  <div class="lg:w-9/12 px-6 lg:pb-2 lg:pt-6 lg:border-l-2 border-customGreen7">
    <ul class="list-disc pl-5">
      <% diary.diary_entries.each do |entry| %>
        <li class="mb-2 mb-4 lg:px-6 py-2 truncate"><%= entry.content %></li>
      <% end %>
    </ul>
  </div>
  <div class="lg:w-1/12 text-center mt-4">
    <%= link_to "詳細", diary_path(diary.id), data: { turbo: false }, class: "text-sm md:text-base bg-customGreen7 rounded-full drop-shadow-lg px-6 py-1 lg:px-4 hover:bg-customGreen6 hover:drop-shadow-lg border-2 border-customGreen2"%>
  </div>
</div>

app/views/diaries/_form.html.erb
  <%= form_with model: diary_form, url: form_url, method: form_method, class: "lg:w-4/5", data: { turbo: false } do |f| %>
    <div class="border-dashed border-2 border-customGreen6 rounded-lg px-8 py-10 mx-auto">
      <div class="text-center">
        <p>今日のよかったことを入力してください</p>
      </div>
      <div>
        <%= render 'shared/error_messages', object: diary_form %>
        <% total_entries.times do |index| %>
          <div class="my-4">
            <% if diary_form.entries_ids.present? %>
              <%= f.hidden_field :entries_ids, multiple: true, value: diary_form.entries_ids[index] %>
            <% end %>
            <%= f.text_area :entries_contents, size: "80x2", id: "diary_form_entries_contents_#{index}", multiple: true, value: diary_form.entries_contents[index], placeholder:"良かったことを入力", class: "w-full border-2 border-customGreen7 rounded-xl bg-customBeige3 py-2 px-4"%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="my-2 text-center">
      <%= f.submit form_method == :post ? '登録する' : '編集する', class: "bg-customGreen6 my-2 px-10 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2"%>
    </div>
  <% end %>

app/views/diaries/edit.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige text-customGreen5 min-h-screen">
  <div class="container mx-auto px-5 py-10">
    <h1 class="text-2xl font-bold text-center pt-4"><%= t('.title') %></h1>
  </div>
  <div class="container mx-auto lg:px-5 py-8">
    <div class="flex justify-center">
      <h2 class="w-4/5"> <%= @diary.date %>(<%= I18n.l(@diary.date, format: '%a') %>)</h2>
    </div>
    <div class="flex justify-center">
      <%= render 'form', diary_form: @diary_form, form_url: diary_path(@diary), form_method: :patch %>
    </div>
  </div>
</div>

app/views/diaries/index.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige text-customGreen5 min-h-screen">
  <div class="container mx-auto px-5 py-10">
    <h1 class="text-2xl font-bold text-center"><%= t('.title') %></h1>
  </div>
  <div class="text-center">
    <%= search_form_for @q, url: diaries_path do |f| %>
      <%= f.date_field :created_at_gteq, include_blank: true, class: 'bg-customBeige3 py-1 rounded-lg text-center'%>
      <span>~</span>
      <%= f.date_field :created_at_lteq_end_of_day, include_blank: true, class:'bg-customBeige3 py-1 rounded-lg text-center'%>
      <%= f.submit '検索', class: 'text-sm mx-2 md:text-base bg-customGreen7 rounded-lg drop-shadow-lg px-6 py-1 lg:px-4 hover:bg-customGreen6 hover:drop-shadow-lg border-2 border-customGreen2' %>
    <% end %>
  </div>
  <div class="container mx-auto py-10 lg:px-16 lg:py-10">
    <div class="flex justify-center md:justify-end text-center my-4">
      <%= link_to new_diary_path, data: { turbo: false } do %>
        <div class="text-sm md:text-base rounded-full drop-shadow-lg px-6 py-1 lg:px-4 hover:bg-customGreen6 hover:drop-shadow-lg border-2 border-customGreen7">
          <i class="fa-solid fa-book inline-block"></i>
          <p class="inline-block">幸せ日記を作成する</p>
        </div>
      <% end %>
    </div>
    <% if @diaries.present? %>
      <%= render partial: 'diary', collection: @diaries %>
    <% else %>
      <p class="text-center"><%= t('.no_result') %></p>
    <% end %>
  </div>
</div>

app/views/diaries/new.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige text-customGreen min-h-screen">
  <div class="container mx-auto px-5 py-10">
    <h1 class="text-2xl font-bold text-center pt-4"><%= t('.title') %></h1>
  </div>
  <div class="container mx-auto lg:px-5 py-8">
    <div class="flex justify-center">
      <h2 class="w-4/5"><%= @date %></h2>
    </div>
    <div class="flex justify-center">
      <%= render 'form', diary_form: @diary_form, form_url: diaries_path, form_method: :post %>
    </div>
  </div>
</div>

app/views/diaries/show.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige text-customGreen5 min-h-screen">
  <div class="container mx-auto px-5 py-10">
    <h1 class="text-2xl font-bold my-8 text-center"><%= t('.title') %></h1>
  </div>
  <div class="container mx-auto lg:px-5 py-8">
    <div class="flex justify-center">
      <h2 class=""><%= @diary.created_at.to_date %>（<%= I18n.l(@diary.created_at, format: '%a') %>）</h2>
    </div>
    <div class="flex justify-center">
      <div class="w-full border-dashed border-2 border-customGreen6 rounded-xl px-8 py-10 lg:mx-16 xl:mx-32">
        <div class="my-4">
          <% @diary.diary_entries.each_with_index do |entry, index| %>
            <p class="bg-customGreen7 text-customGreen5 rounded-xl py-2 px-4 mb-6"><%= index+1 %>. <%= entry.content %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="text-center my-8">
      <%= link_to "編集", edit_diary_path(@diary), data: { turbo: false }, class: "bg-customGreen6 text-customGreen5 mx-6 my-2 px-5 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2" %>
      <%= link_to "削除", diary_path(@diary), class:"bg-customGreen6 text-customGreen5 mx-6 my-2 px-5 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2", data: { turbo_method: :delete, turbo_confirm: "日記を削除しますか?" } %>
    </div>
  </div>
</div>