config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end

    resources :dashboards, only: %i[index]
    root 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :flowers
    resources :questions
    resources :monthly_themes
    resources :theme_resources
  end

  resources :self_esteem_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :self_discovery_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :diaries
  resource :mypage, only: %i[show]
  resource :garden, only: %i[show]
  root 'static_pages#top'
  get 'top', to:'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :questions, only: [:index] do
    collection do
      post :calculate
      get :result
    end
  end
  resources :encouragement_requests, only: %i[index new create show edit update destroy] do
    resources :encouragement_messages, only: [:index]
    collection do
      get 'select_image'
      get 'draft'
    end
    member do
      patch 'status_update'
    end
  end
  resources :encouragement_messages, only: %i[ new create show edit update destroy]
end

app/views/shared/_before_login_header.html.erb
<header class="bg-customGreen5 flex flex-row justify-between items-center h-20">
  <div class="text-customGreen3 ml-2 md:mx-6 text-xl md:text-2xl font-bold">
    <%= link_to "JustBe U", "/" %>
  </div>
  <div class="flex items-center space-x-1 md:mx-6 text-customGreen2">
    <%= link_to new_user_session_path, class:'mx-2 hidden md:flex md:flex-col' do %>
      <i class="fa-solid fa-right-to-bracket text-center text-xl"></i>
      <p class="text-sm font-semibold"><%= t('devise.sessions.new.sign_in') %></p>
    <% end %>
    <%= link_to new_user_registration_path, class:'mx-2 hidden md:flex md:flex-col' do %>
      <i class="fa-solid fa-user-plus text-center text-xl"></i>
      <p class="text-sm font-semibold"><%= t('devise.shared.links.sign_up') %></p>
    <% end %>
    <details class="dropdown dropdown-end hidden md:flex md:flex-col">
      <summary class="text-customGreen2 m-1 btn bg-customGreen5 border-none hover:bg-customGreen5">
        <i class="fa-solid fa-bars h-6 w-8"></i>
      </summary>
        <ul class="dropdown-content z-[1] menu px-4 py-2 shadow rounded-xl bg-customGreen5 w-80 text-customGreen2 mt-3">
          <li class="hover:bg-customGreen hover:rounded-xl">
            <%= link_to "自己否定度診断", questions_path, class:"text-sm font-semibold mx-2", data: { turbo: false }%>
          </li>
          <li class="hover:bg-customGreen hover:rounded-xl">
            <%= link_to "みんなの励ましクエスト", encouragement_requests_path, data: { turbo: false }, class: "text-sm font-semibold mx-2"%>
          </li>
        </ul>
    </details>

    <nav class="md:hidden">
      <details class="dropdown dropdown-end">
        <summary class="text-customGreen2 m-1 btn bg-customGreen5 border-none hover:bg-customGreen5">
          <i class="fa-solid fa-bars h-6 w-8"></i>
        </summary>
          <ul class="dropdown-content z-[1] menu px-4 py-2 shadow rounded-xl bg-customGreen5 w-80 text-customGreen2 mt-3">
            <li class="hover:bg-customGreen hover:rounded-xl">
              <%= link_to new_user_session_path, class:'flex items-center mx-2' do %>
                <i class="fa-solid fa-right-to-bracket text-center text-lg"></i>
                <p class="text-sm font-semibold"><%= t('devise.sessions.new.sign_in') %></p>
              <% end %>
            </li>
            <li class="hover:bg-customGreen hover:rounded-xl mt-2">
              <%= link_to new_user_registration_path, class:'flex items-center mx-2' do %>
                <i class="fa-solid fa-user-plus text-center text-lg"></i>
                <p class="text-sm font-semibold"><%= t('devise.shared.links.sign_up') %></p>
              <% end %>
            </li>
            <li class="hover:bg-customGreen hover:rounded-xl border-t-2 border-customGreen4 mt-4 pt-2">
              <%= link_to "自己否定度診断", questions_path, class:"text-sm font-semibold mx-2", data: { turbo: false }%>
            </li>
            <li class="hover:bg-customGreen hover:rounded-xl">
              <%= link_to "みんなの励ましクエスト", encouragement_requests_path, data: { turbo: false }, class: "text-sm font-semibold mx-2"%>
            </li>
          </ul>
      </details>
    </nav>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages", class="p-4 text-sm text-red-800 bg-red-100 dark:bg-red-100 dark:text-red-800">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == 'success' || message_type == 'notice' %>
    <div class="p-4 text-sm text-emerald-800 bg-emerald-100 dark:bg-emerald-100 dark:text-emerald-800" role="alert">
      <%= message %>
    </div>
  <% elsif message_type == 'danger' %>
    <div class="p-4 text-sm text-red-800 bg-red-100 dark:bg-red-100 dark:text-red-800" role="alert">
      <%= message %>
    </div>
  <% elsif message_type == 'warning' %>
    <div class="p-4 text-sm text-yellow-800 bg-yellow-100 dark:bg-yellow-100 dark:text-yellow-800" role="alert">
      <%= message %>
    </div>
  <% else %>
    <div class="p-4 text-sm text-sky-800 bg-sky-100 dark:bg-sky-100 dark:text-sky-800" role="alert"><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="bg-customGreen5 flex flex-col justify-between items-center h-24 content-end">
      <!-- nav - start -->
      <nav class="flex flex-wrap justify-center gap-x-4 gap-y-2 md:justify-start mt-6 text-customGreen6">
        <%= link_to t('defaults.terms_of_use'), terms_path, class: "transition duration-100 hover:text-orange-300 active:text-indigo-600" %>
        <%= link_to t('defaults.privacy_policy'), privacy_path, class: "transition duration-100 hover:text-orange-300 active:text-indigo-600" %>
        <%= link_to t('defaults.contact'), "https://forms.gle/VNeV9vCgs4keGWoe8", target: "_blank", rel: "noopener noreferrer", class: "transition duration-100 hover:text-orange-300 active:text-indigo-600" %>
      </nav>
      <!-- nav - end -->
      <div class="text-center text-sm text-teal-950 mb-2">© 2023 - Present JustBe U. All rights reserved.</div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class="bg-customGreen5 flex flex-row justify-between items-center h-20">
  <div class="text-customGreen3 mx-6 text-2xl font-bold">
      <%= link_to "JustBe U", "/", data: { turbo: false }%>
  </div>
  <div class="flex items-center space-x-4 mx-4">
    <div class="hidden md:block text-customGreen2 mx-4 text-customGreen2">
      <%= link_to "自己否定度診断", questions_path, data: { turbo: false }%>
    </div>
    <nav>
      <details class="dropdown dropdown-end">
        <summary class="text-customGreen2 m-1 btn bg-customGreen5 border-none hover:bg-customGreen5">
          <i class="fa-solid fa-bars h-6 w-8"></i>
        </summary>
        <ul class="dropdown-content z-[1] menu px-6 py-4 shadow bg-customGreen5 rounded-box w-80 text-customGreen2 mt-3">
          <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to "マイページ", mypage_path, data: { turbo: false }%></li>
          <li>
            <details>
              <summary class="hover:bg-neutral-600 hover:rounded-xl">トレーニング</summary>
                <ul>
                  <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to "- 自己受容トレーニング", new_self_esteem_training_path, data: { turbo: false }%></li>
                  <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to "- 自己発見トレーニング", new_self_discovery_training_path, data: { turbo: false }%></li>
                </ul>
            </details>
          </li>
          <li>
            <details>
              <summary class="hover:bg-neutral-600 hover:rounded-xl">幸せ日記</summary>
                <ul>
                  <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to "- 幸せ日記一覧", diaries_path, data: { turbo: false }%></li>
                  <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to "- 今日の幸せ日記を作成", new_diary_path, data: { turbo: false }%></li>
                </ul>
            </details>
          </li>
          <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to "みんなの励ましクエスト", encouragement_requests_path, data: { turbo: false }%></li>
          <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to "励ましリクエスト作成", select_image_encouragement_requests_path, data: { turbo: false }%></li>
          <li class="md:hidden hover:bg-neutral-600 hover:rounded-xl"><%= link_to "自己否定度診断", questions_path, data: { turbo: false }%></li>
          <li class="hover:bg-neutral-600 hover:rounded-xl"><%= link_to t('defaults.sign_out'), destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか?" } %></li>
        </ul>
      </details>
    </nav>
  </div>
</header>