config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end

    resources :dashboards, only: %i[index]
    root 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :flowers
    resources :questions
    resources :monthly_themes
    resources :theme_resources
  end

  resources :self_esteem_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :self_discovery_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :diaries
  resource :mypage, only: %i[show]
  resource :garden, only: %i[show]
  root 'static_pages#top'
  get 'top', to:'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :questions, only: [:index] do
    collection do
      post :calculate
      get :result
    end
  end
  resources :encouragement_requests, only: %i[index new create show edit update destroy] do
    resources :encouragement_messages, only: [:index]
    collection do
      get 'select_image'
      get 'draft'
    end
    member do
      patch 'status_update'
    end
  end
  resources :encouragement_messages, only: %i[ new create show edit update destroy]
end

app/models/encouragement_request.rb
class EncouragementRequest < ApplicationRecord
  has_one_attached :request_image
  belongs_to :user
  has_many :encouragement_messages, dependent: :destroy
  validates :text, presence: true, length: { maximum: 150 }
  validates :status, presence: true
  validates :background_id, presence: true, numericality: { only_integer: true }
  validates :request_image, presence: true, blob: { content_type: ['image/png'] }
  enum status: { draft: 0, public_status: 1 }
end

app/controllers/encouragement_requests_controller.rb
class EncouragementRequestsController < ApplicationController
  before_action :set_encouragement_request, only: %i[show edit update destroy status_update]
  skip_before_action :authenticate_user!, only: %i[index]
  def index
    if params[:message_id].present?
      @encouragement_message = EncouragementMessage.find(params[:message_id])
    end
    @encouragement_requests = EncouragementRequest.where(status: 'public_status').includes(:user).order(created_at: :desc).page(params[:page]).per(18)
  end

  def draft
    @encouragement_requests = current_user.encouragement_requests.where(status: 'draft').includes(:user).order(created_at: :desc).page(params[:page]).per(18)
  end

  def select_image; end

  def new
    @encouragement_request = EncouragementRequest.new
    # @encouragement_request.image_id = params[:image_id]
    @image_id = params[:image_id].to_i
  end

  def create
    @encouragement_request = current_user.encouragement_requests.build(encouragement_request_params)
    @image_id = @encouragement_request.background_id
    image = ImageCreator.build(@encouragement_request.text, @encouragement_request.background_id)
    image_path = image.path
    @encouragement_request.request_image.attach(io: File.open(image_path), filename: 'request_image.png', content_type: 'image/png')

    if @encouragement_request.save
      redirect_to encouragement_request_path(@encouragement_request), success: '画像を作成しました'
    else
      flash.now[:danger] = '画像の作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    Rails.logger.info "Encouragement Request Image URL: #{url_for(@encouragement_request.request_image)}"
  end

  def edit; end

  def update
    @encouragement_request.update(encouragement_request_params)
    image = ImageCreator.build(@encouragement_request.text, @encouragement_request.background_id)
    image_path = image.path
    @encouragement_request.request_image.attach(io: File.open(image_path), filename: 'request_image.png', content_type: 'image/png')
    if @encouragement_request.save
      redirect_to encouragement_request_path(@encouragement_request), success: '画像を作成しました'
    else
      flash.now[:danger] = '画像の作成に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def status_update
    if @encouragement_request.update(status: status_params)
      redirect_to encouragement_request_path(@encouragement_request), success: 'ステータスを変更にしました'
    else
      flash.now[:danger] = 'ステータスの変更に失敗しました'
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @encouragement_request.destroy
    redirect_to encouragement_requests_path, success: '画像を削除しました'
  end

  private

  def set_encouragement_request
    @encouragement_request = current_user.encouragement_requests.find_by(id: params[:id])
  end

  def encouragement_request_params
    params.require(:encouragement_request).permit(:text, :request_image, :background_id, :status)
  end

  def status_params
    if params[:commit] == '公開する'
      'public_status'
    else
      'draft'
    end
  end
end

app/views/encouragement_requests/_darft.html.erb
<div class="border-2 border-customGreen2 rounded-lg p-4">
  <%= image_tag encouragement_request.request_image, size: '400x300', class:"mx-auto"%>
  <%= form_with model: encouragement_request, url: status_update_encouragement_request_path(encouragement_request) do |f| %>
    <div class="text-center my-2">
      <%= f.submit '公開する', class: "btn btn-wide btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6" %>
    </div>
    <div class="text-center mb-2">
    <%= link_to t('defaults.edit'), edit_encouragement_request_path(encouragement_request), class: "btn btn-wide btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6"%>
    </div>
  <% end%>
</div>

app/views/encouragement_requests/_encouragement_request.html.erb
<div class="border-2 border-customGreen2 bg-customBeige3 rounded-lg p-4">
  <%= image_tag encouragement_request.request_image, size: '400x300', class:"mx-auto"%>
  <i class="fa-regular fa-user text-customGreen text-left"></i>
  <%=  encouragement_request.user.name %>
  <% if current_user&.own?(encouragement_request) %>
    <%= link_to encouragement_request_path(encouragement_request), class:"mx-1", data: { turbo_method: :delete, turbo_confirm: "励ましリクエストを削除すると、送られた励ましメッセージも一緒に削除されます。本当に削除しますか？" } do %>
      <i class="fa-regular fa-trash-can text-customGreen text-right"></i>
    <% end %>
    <%= link_to edit_encouragement_request_path(encouragement_request), class:"mx-1" do %>
      <i class="fa-solid fa-pencil text-customGreen"></i>
    <% end %>
  <% end %>
  <%= link_to '励ましメッセージ一覧', encouragement_request_encouragement_messages_path(encouragement_request), class: "block text-center bg-customGreen6 my-2 px-2 py-1 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2" %>
  <%= link_to '励ましメッセージを送る', new_encouragement_message_path(request_id:encouragement_request.id), class: "block text-center bg-customGreen6 my-2 px-2 py-1 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2" %>
</div>

app/views/encouragement_requests/draft.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige min-h-screen text-customGreen5">
  <div class="container mx-auto px-2 sm:px-5 py-10">
    <h1 class="text-2xl font-bold text-center my-10"><%= t('.title') %></h1>
  </div>
  <div class="container mx-auto px-4 py-10">
    <% if @encouragement_requests.present? %>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
        <%= render partial: 'darft', collection: @encouragement_requests, as: :encouragement_request %>
      </div>
      <div class="flex items-center justify-center mt-4 mb-10">
        <%= paginate @encouragement_requests, window: 2 %>
      </div>
    <% else %>
      <p class="text-center">下書きがありません</p>
    <% end %>
  </div>
</div>

app/views/encouragement_requests/edit.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige min-h-screen text-customGreen5">
  <div class="container mx-auto px-5 py-10">
    <h1 class="text-2xl font-bold text-center pt-4"><%= t('.title') %></h1>
  </div>
  <div class="container mx-auto px-5 py-10">
    <div class="flex flex-col items-center  w-full">
      <%= image_tag "#{@encouragement_request.background_id}.png", size: '400x300' %>
    </div>
    <div class="container mx-auto px-5 py-10">
      <%= form_with model: @encouragement_request, data: { turbo: false } do |f| %>
        <%= render 'shared/error_messages', object: @encouragement_request %>
        <div class="my-2 sm:w-2/3 lg:w-2/5 sm:mx-auto">
          <%= f.label :text, "画像に入れるテキストを入力", class: "block text-sm md:text-base text-left my-2 text-customGreen" %>
          <%= f.text_area :text, size: "40x4", class: "w-full bg-customBeige3 border-2 border-customGreen7 sm:p-2 rounded-lg", placeholder:"例）励ましてください"%>
        </div>
        <div class="my-2 text-center">
          <%= f.select :status, EncouragementRequest.statuses_i18n.invert, {}, class: "select select-bordered w-full max-w-xs border-2 border-customGreen7 bg-customBeige3 text-slate-400" %>
        </div>
        <%= f.hidden_field :background_id, value: @encouragement_request.background_id%>
        <div class="actions text-center">
          <%= f.submit t('defaults.edit'), class: "bg-customGreen6 my-2 px-10 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/encouragement_requests/index.html.erb
<% content_for(:title, t('.title'))%>
<% if @encouragement_message.present? %>
  <% assign_meta_tags image: rails_blob_url(@encouragement_message.message_image, only_path: false)%>
<% end %>
<div class="bg-customBeige min-h-screen text-customGreen5">
  <div class="container mx-auto px-2 sm:px-5 py-10">
    <h1 class="text-2xl font-bold text-center my-10"><%= t('.title') %></h1>
  </div>
  <div class="container mx-auto px-4 py-10">
    <% if @encouragement_requests.present? %>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
        <%= render partial: 'encouragement_request', collection: @encouragement_requests %>
      </div>
      <div class="flex items-center justify-center mt-4 mb-10">
        <%= paginate @encouragement_requests, window: 2 %>
      </div>
    <% else %>
      <p class="text-center"><%= t('.no_result') %></p>
    <% end %>
  </div>
</div>

app/views/encouragement_requests/new.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige min-h-screen text-customGreen5">
  <div class="container mx-auto px-5 py-6">
    <h1 class="text-2xl font-bold text-center pt-4"><%= t('.title') %></h1>
    <h1 class="text-customGreen text-lg font-bold text-center pt-4 my-6">STEP②-メッセージの入力</h1>
  </div>
  <div class="container mx-auto px-5 py-10">
    <div class="flex flex-col items-center  w-full">
      <p class="text-customGreen2">あなたが選択した画像</p>
      <%= image_tag "#{@image_id}.png", size: '400x300' %>
    </div>
    <div class="container mx-auto sm:px-5 py-10">
      <%= form_with model: @encouragement_request, data: { turbo: false } do |f| %>
        <%= render 'shared/error_messages', object: @encouragement_request %>
        <div class="my-2 sm:w-2/3 lg:w-2/5 sm:mx-auto">
          <%= f.label :text, "画像に入れるテキストを入力", class: "block text-sm md:text-base text-left my-2 text-customGreen" %>
          <%= f.text_area :text, size: "40x4", class: "w-full bg-customBeige3 border-2 border-customGreen7 sm:p-2 rounded-lg", placeholder:"例）ちょっと落ち込んでいます。元気づけてくれる言葉を待っています。"%>
        </div>
        <div class="my-2 text-center">
          <%= f.select :status, options_for_select([["ステータスを選択", nil, { disabled: true, selected: true }]] + EncouragementRequest.statuses_i18n.invert.to_a), {}, class: "select select-bordered w-full max-w-xs border-2 border-customGreen7 bg-customBeige3 text-slate-400" %>
        </div>
        <%= f.hidden_field :background_id, value: @image_id%>
        <div class="grid grid-rows-2 grid-flow-col gap-4 my-6">
          <%= f.submit "作成する", class: "mx-auto btn btn-wide btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6 hover:bg-customGreen7 hover:border-customGreen2" %>
          <%= link_to "画像を選択し直す", select_image_encouragement_requests_path, class: "mx-auto text-center btn btn-wide btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6 hover:bg-customGreen7 hover:border-customGreen2"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/encouragement_requests/select_image.html.erb
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige min-h-screen text-customGreen5">
  <div class="container mx-auto px-5 py-6">
    <h1 class="text-2xl font-bold text-center pt-4"><%= t('encouragement_requests.new.title') %></h1>
    <h1 class="text-customGreen text-lg font-bold text-center pt-4 my-6">STEP①-<%= t('.title') %></h1>
    <p class="text-customGreen my-4 text-center text-sm md:text-base">使用したい背景を以下の中から一つ選択してください</p>
  </div>
  <div class="container mx-auto px-5 py-10">
    <div class="sm:grid sm:grid-cols-2 sm:gap-2">
      <div>
        <p class="text-xl text-center font-bold mb-4">イメージ１</p>
        <figure class="flex justify-center px-6 mt-2">
          <%= image_tag '1.png', size: '400x300' %>
        </figure>
        <div class="items-center text-center mb-10">
          <%= button_to "これにする", new_encouragement_request_path, { method: :get, params: {image_id: 1}, class: "text-sm my-2 px-8 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2" } %>
        </div>
      </div>
      <div>
        <p class="text-xl text-center font-bold mb-4">イメージ2</p>
        <figure class="flex justify-center px-6 mt-2">
          <%= image_tag '2.png', size: '400x300' %>
        </figure>
        <div class="items-center text-center mb-10">
          <%= button_to "これにする", new_encouragement_request_path, { method: :get, params: {image_id: 2}, class: "text-sm my-2 px-10 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2" } %>
        </div>
      </div>
      <div>
        <p class="text-xl text-center font-bold mb-4">イメージ3</p>
        <figure class="flex justify-center px-6 mt-2">
          <%= image_tag '3.png', size: '400x300' %>
        </figure>
        <div class="items-center text-center mb-10">
          <%= button_to "これにする", new_encouragement_request_path, { method: :get, params: {image_id: 3}, class: "text-sm my-2 px-10 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2" } %>
        </div>
      </div>
      <div>
        <p class="text-xl text-center font-bold mb-4">イメージ4</p>
        <figure class="flex justify-center px-6 mt-2">
          <%= image_tag '4.png', size: '400x300' %>
        </figure>
        <div class="items-center text-center mb-10">
          <%= button_to "これにする", new_encouragement_request_path, { method: :get, params: {image_id: 4}, class: "text-sm my-2 px-10 py-2 rounded-full drop-shadow-lg hover:bg-customGreen7 hover:drop-shadow-lg border-2 border-customGreen2" } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/encouragement_requests/show.html.erb
<% assign_meta_tags url: new_encouragement_message_url(request_id: @encouragement_request.id), image: rails_blob_url(@encouragement_request.request_image, only_path: false)%>
<% content_for(:title, t('.title'))%>
<div class="bg-customBeige min-h-screen text-customGreen5">
  <div class="container mx-auto px-5 py-10">
    <h1 class="text-2xl font-bold text-center pt-4"><%= t('.title') %></h1>
  </div>
  <div class="container mx-auto px-5 py-10">
    <div class="flex flex-col items-center  w-full">
      <%= image_tag @encouragement_request.request_image, size: '600x500' %>
    </div>
  </div>
  <div class="container mx-auto px-2 pb-10">
    <p class="text-center text-xs sm:text-base my-6 mx-4">作成した励ましリクエストカードをシェアーしてみんなから励ましのメッセージを受け取りましょう!</p>
    <%= form_with model: @encouragement_request, url: status_update_encouragement_request_path(@encouragement_request) do |f| %>
      <div class="twitter ms:font-bold text-white text-center text-xs mb-2">
        <%= link_to "https://x.com/share?url=https://www.justbe-u.com/encouragement_messages/new?request_id=#{@encouragement_request.id}&text=リンクから#{@encouragement_request.user.name}さんに励ましのメッセージカードを送って元気づけましょう！%0a%0a %23JustBeU %23自己受容", target: '_blank', class: "btn btn-wide btn-sm rounded-full bg-gray-500 hover:bg-gray-600" do %>
          <i class="fa-brands fa-x-twitter"></i>シェア
        <% end %>
      </div>
      <% if @encouragement_request.public_status? %>
        <div class="text-center mb-2">
          <%= f.submit '下書き', class: "btn btn-wide btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6 hover:bg-customGreen7 hover:border-customGreen2" %>
        </div>
      <%else%>
        <div class="text-center mb-2">
          <%= f.submit '公開する', class: "btn btn-wide btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6 hover:bg-customGreen7 hover:border-customGreen2" %>
        </div>
      <% end%>
      <div class="text-center mb-2">
        <%= link_to 'テキストを編集する', edit_encouragement_request_path(@encouragement_request),  class: "btn btn-wide  btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6 hover:bg-customGreen7 hover:border-customGreen2" %>
      </div>
      <div class="text-center mb-2">
        <%= link_to "保存を取り消す", encouragement_request_path(@encouragement_request), class:"btn btn-wide btn-sm text-customGreen border-1 border-customGreen2 bg-customGreen6 hover:bg-customGreen7 hover:border-customGreen2", data: { turbo_method: :delete, turbo_confirm: "画像を削除しますか?" } %>
      </div>
    <% end %>
  </div>
</div>