config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    devise_scope :user do
      get 'login', to: 'sessions#new'
      post 'login', to: 'sessions#create'
      delete 'logout', to: 'sessions#destroy'
    end

    resources :dashboards, only: %i[index]
    root 'dashboards#index'
    resources :users, only: %i[index show edit update destroy]
    resources :flowers
    resources :questions
    resources :monthly_themes
    resources :theme_resources
  end

  resources :self_esteem_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :self_discovery_trainings, only: %i[new] do
    collection do
      get 'result'
    end
  end
  resources :diaries
  resource :mypage, only: %i[show]
  resource :garden, only: %i[show]
  root 'static_pages#top'
  get 'top', to:'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :questions, only: [:index] do
    collection do
      post :calculate
      get :result
    end
  end
  resources :encouragement_requests, only: %i[index new create show edit update destroy] do
    resources :encouragement_messages, only: [:index]
    collection do
      get 'select_image'
      get 'draft'
    end
    member do
      patch 'status_update'
    end
  end
  resources :encouragement_messages, only: %i[ new create show edit update destroy]
end

app/models/self_discovery_training.rb
class SelfDiscoveryTraining < ApplicationRecord
  belongs_to :user
  validates :trained_at, presence: true
end

app/controllers/self_discovery_trainings_controller.rb
class SelfDiscoveryTrainingsController < ApplicationController
  before_action :set_token, only: :result

  def new; end

  def result
    # 今日のトレーニング回数を取得
    today_trainings_count = current_user.self_discovery_trainings.where('trained_at >= ?', Time.zone.now.beginning_of_day).count

    if text_params.length > 50
      flash.now[:danger] = t('.text_limit')
      render :new
      return
    end

    if today_trainings_count < 2
      # OpenAIへのリクエストを行い、結果を取得
      additional_prompt = '自己分析の専門家として、ユーザーの短所を60文字以内で長所に変換してください。具体例を用い、[短所]は実は[長所]です。'
      Rails.logger.info 'Preparing to send request to OpenAI...'
      @client = OpenAI::Client.new(access_token: @api_key)
      response = @client.chat(
        parameters: {
          model: 'gpt-3.5-turbo',
          messages: [
            { role: 'system', content: additional_prompt },
            { role: 'user', content: text_params }
          ]
        }
      )
      Rails.logger.info "Received response from OpenAI: #{response.inspect}"
      @chat = response.dig('choices', 0, 'message', 'content') if response.present?

      if @chat.present?
        current_user.self_discovery_trainings.create!(trained_at: Time.current)
      else
        flash.now[:danger] = t('.fail')
        render :new
      end
    else
      redirect_to root_path, danger: t('.over_the_limit')
    end
  end

  private

  def set_token
    @api_key = Rails.application.credentials.dig(:openai, :api_key)
  end

  def text_params
    @query = params[:text]
  end
end

app/views/self_discovery_trainings/new.html.erb
<% content_for( :title, t('.title'))%>
<div class="bg-customBeige text-customGreen5 min-h-screen">
  <div class="input-area container mx-auto px-5 py-10">
      <div class="text-center mt-5">
          <h1 class="font-bold text-xl sm:text-3xl py-4 my-4">自己発見トレーニング</h1>
          <p class="text-sm md:text-base pt-4 pb-8 mx-2 md:mx-0">自身がマイナスだと感じる特性（性格）をポジティブな視点から見るトレーニングになります</p>
      </div>
      <div class="flex justify-center">
        <%= form_with(url: result_self_discovery_trainings_path, method: :get, class: "grid gap-4", data: { turbo: false })do |f| %>
          <div class="sm:px-8 sm:py-10 sm:mx-auto">
            <div class="lg:w-2/3 lg:mx-auto">
              <%= f.label '自身がマイナスだと感じる特性（性格)を一つ入力してください' %>
              <%= f.text_area :text, size: "80x3", class: "w-full bg-customBeige3 border-2 border-customGreen3 p-2 rounded-lg text-sm md:text-base", placeholder:"例）優柔不断な部分がある、意志が弱い部分がある、心配性だ、計画性がない...etc" %>
              <p class="text-xs text-rose-900">*1日にトレーニングできる回数は2回までです。</p>
              <p class="text-xs text-rose-900">*AIからの返答が10~20秒ほどかかります。</p>
              <p class="text-xs text-rose-900">*50文字以内で入力してください</p>
            </div>
          </div>
          <div class="my-2 text-center">
            <%= f.submit '変換', class: "bg-customGreen5 text-customBeige px-6 py-2 rounded-full drop-shadow-lg hover:bg-customGreen hover:drop-shadow-lg border-2 border-customGreen2", id: "convertButton2"%>
          </div>
        <% end %>
      </div>
  </div>
  <div class="animation-area hidden fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-50 drop-shadow-2xl" id="animationArea2">
    <%= image_tag 'flower1.gif', size: "300x300", id: 'animationGif', class: 'border-2 border-customBeige2 rounded-full drop-shadow-lg'%>
  </div>
</div>

app/views/self_discovery_trainings/result.html.erb
<% content_for( :title, t('.title'))%>
<div class="bg-customBeige text-customGreen5 min-h-screen">
  <div class="container mx-auto px-5 py-10">
    <h1 class="text-2xl md:text-3xl font-bold text-center mt-10">自己探索の結果</h1>
  </div>
  <div class="container mx-auto px-2 py-4 md:py-10 md:px-5 lg:px-24 xl:px-32">
    <div class="flex items-end hidden md:inline-flex">
      <div class="w-1/5 text-center">
        <%= image_tag 'rabbit.png', size:'206x256', class:'w-3/5 mx-auto'%>
      </div>
      <div class="chat chat-start w-4/5 pl-8">
        <div class="chat-bubble py-10 px-10 bg-customGreen7">
          <p class="text-customGreen text-center tracking-wide leading-normal"><%= @chat %></p>
        </div>
      </div>
    </div>
    <div class="flex flex-col md:hidden">
      <div class="border border-customGreen2 bg-customGreen7 rounded-xl px-2 py-10">
          <p class="text-xs text-customGreen text-center tracking-wide leading-normal"><%= @chat %></p>
      </div>
      <div class="text-center">
        <%= image_tag 'rabbit.png', size:'80x100', class:'w-1/3 sm:w-1/5 mx-auto my-8'%>
      </div>
    </div>
  </div>
  <div class="container mx-auto py-2 px-5 md:py-10">
    <div class="bg-customGreen7 border-2 border-customGreen2 shadow-lg rounded-full text-center w-1/4 mx-auto mb-20 py-2 hover:bg-customGreen6 hidden lg:block">
      <%= link_to '自己発見トレーニングに戻る', new_self_discovery_training_path, data: { turbo: false }%>
    </div>
    <div class="g-customGreen7 border-2 border-customGreen2 shadow-lg rounded-full text-center w-2/4 mx-auto my-4 py-2 hover:bg-customGreen6 lg:hidden">
      <%= link_to '戻る', new_self_discovery_training_path, data: { turbo: false }%>
    </div>
  </div>
</div>